export const escrowAbi = [
	{
		type: "function",
		name: "createBounty",
		stateMutability: "nonpayable",
		inputs: [
			{ name: "repositoryHash", type: "bytes32" },
			{ name: "issueNumber", type: "uint32" },
			{ name: "deadline", type: "uint64" },
			{ name: "reviewWindow", type: "uint64" },
		],
		outputs: [{ name: "bountyId", type: "uint256" }],
	},
	{
		type: "function",
		name: "fundBounty",
		stateMutability: "nonpayable",
		inputs: [
			{ name: "bountyId", type: "uint256" },
			{ name: "rewardAmount", type: "uint128" },
		],
		outputs: [],
	},
	{
		type: "function",
		name: "submitClaim",
		stateMutability: "nonpayable",
		inputs: [
			{ name: "bountyId", type: "uint256" },
			{ name: "recipient", type: "address" },
			{ name: "prNumber", type: "uint256" },
			{ name: "commitHash", type: "bytes32" },
			{ name: "expiresAt", type: "uint64" },
			{ name: "nonce", type: "uint256" },
			{ name: "signature", type: "bytes" },
		],
		outputs: [],
	},
	{
		type: "function",
		name: "approveClaim",
		stateMutability: "nonpayable",
		inputs: [{ name: "bountyId", type: "uint256" }],
		outputs: [],
	},
	{
		type: "function",
		name: "finalizeClaim",
		stateMutability: "nonpayable",
		inputs: [{ name: "bountyId", type: "uint256" }],
		outputs: [],
	},
	{
		type: "function",
		name: "disputeClaim",
		stateMutability: "nonpayable",
		inputs: [{ name: "bountyId", type: "uint256" }],
		outputs: [],
	},
	{
		type: "function",
		name: "resolveDispute",
		stateMutability: "nonpayable",
		inputs: [
			{ name: "bountyId", type: "uint256" },
			{ name: "claimantBps", type: "uint16" },
		],
		outputs: [],
	},
	{
		type: "function",
		name: "refundExpired",
		stateMutability: "nonpayable",
		inputs: [{ name: "bountyId", type: "uint256" }],
		outputs: [],
	},
	{
		type: "function",
		name: "bounties",
		stateMutability: "view",
		inputs: [{ name: "", type: "uint256" }],
		outputs: [
			{ name: "creator", type: "address" },
			{ name: "amount", type: "uint128" },
			{ name: "feeAmount", type: "uint128" },
			{ name: "totalFunded", type: "uint128" },
			{ name: "deadline", type: "uint64" },
			{ name: "reviewWindow", type: "uint64" },
			{ name: "reviewEnds", type: "uint64" },
			{ name: "issueNumber", type: "uint32" },
			{ name: "repositoryHash", type: "bytes32" },
			{ name: "claimant", type: "address" },
			{ name: "claimDigest", type: "bytes32" },
			{ name: "status", type: "uint8" },
			{ name: "approved", type: "bool" },
		],
	},
	{
		type: "function",
		name: "feeBps",
		stateMutability: "view",
		inputs: [],
		outputs: [{ type: "uint16" }],
	},
	{
		type: "function",
		name: "feeTreasury",
		stateMutability: "view",
		inputs: [],
		outputs: [{ type: "address" }],
	},
	{
		type: "function",
		name: "calculateFee",
		stateMutability: "view",
		inputs: [{ name: "rewardAmount", type: "uint128" }],
		outputs: [{ type: "uint128" }],
	},
	{
		type: "function",
		name: "setFeeBps",
		stateMutability: "nonpayable",
		inputs: [{ name: "newFeeBps", type: "uint16" }],
		outputs: [],
	},
	{
		type: "function",
		name: "setFeeTreasury",
		stateMutability: "nonpayable",
		inputs: [{ name: "newTreasury", type: "address" }],
		outputs: [],
	},
	{
		type: "event",
		name: "BountyCreated",
		inputs: [
			{ indexed: true, name: "bountyId", type: "uint256" },
			{ indexed: true, name: "creator", type: "address" },
			{ indexed: true, name: "repositoryHash", type: "bytes32" },
			{ indexed: false, name: "issueNumber", type: "uint32" },
			{ indexed: false, name: "deadline", type: "uint64" },
		],
	},
	{
		type: "event",
		name: "BountyFunded",
		inputs: [
			{ indexed: true, name: "bountyId", type: "uint256" },
			{ indexed: false, name: "rewardAmount", type: "uint128" },
			{ indexed: false, name: "feeAmount", type: "uint128" },
			{ indexed: false, name: "totalAmount", type: "uint128" },
		],
	},
	{
		type: "event",
		name: "PlatformFeePaid",
		inputs: [
			{ indexed: true, name: "bountyId", type: "uint256" },
			{ indexed: true, name: "treasury", type: "address" },
			{ indexed: false, name: "amount", type: "uint128" },
		],
	},
	{
		type: "event",
		name: "BountyCancelled",
		inputs: [{ indexed: true, name: "bountyId", type: "uint256" }],
	},
	{
		type: "event",
		name: "ClaimSubmitted",
		inputs: [
			{ indexed: true, name: "bountyId", type: "uint256" },
			{ indexed: true, name: "claimant", type: "address" },
			{ indexed: false, name: "prNumber", type: "uint256" },
			{ indexed: false, name: "commitHash", type: "bytes32" },
		],
	},
	{
		type: "event",
		name: "ClaimApproved",
		inputs: [{ indexed: true, name: "bountyId", type: "uint256" }],
	},
	{
		type: "event",
		name: "ClaimDisputed",
		inputs: [{ indexed: true, name: "bountyId", type: "uint256" }],
	},
	{
		type: "event",
		name: "BountyPaid",
		inputs: [
			{ indexed: true, name: "bountyId", type: "uint256" },
			{ indexed: true, name: "recipient", type: "address" },
			{ indexed: false, name: "amount", type: "uint128" },
		],
	},
	{
		type: "event",
		name: "BountyRefunded",
		inputs: [
			{ indexed: true, name: "bountyId", type: "uint256" },
			{ indexed: false, name: "amount", type: "uint128" },
		],
	},
] as const;
